from __future__ import annotations

from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from pathlib import Path
import sqlite3

import pytest

import migrations
from migrations import MigrationLock, SCHEMA_VERSION, integrity_check, migrate, prune_backups
from storage import Storage


# Independently frozen v1 schema, not generated by the new migration functions.
V1_SQL = """
CREATE TABLE chats (id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,
 name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,
 updated_at TEXT NOT NULL,UNIQUE(kind,name));
CREATE TABLE messages (id TEXT PRIMARY KEY,chat_id INTEGER NOT NULL REFERENCES chats(id),
 role TEXT NOT NULL,direction TEXT NOT NULL,content TEXT NOT NULL,status TEXT NOT NULL,
 source_key TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,error_message TEXT);
CREATE INDEX idx_messages_chat_created ON messages(chat_id,created_at,id);
CREATE INDEX idx_messages_chat_role_status ON messages(chat_id,role,status);
CREATE TABLE schema_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT INTO schema_meta VALUES('schema_version','1');
INSERT INTO chats VALUES(1,'private','Synthetic Friend',1,'2026-01-01','2026-01-01');
INSERT INTO messages VALUES('old',1,'user','incoming','synthetic history','received',
 'old-source','2026-01-01','2026-01-01',NULL);
PRAGMA user_version=1;
"""


def make_v1(root: Path) -> Path:
    path = root / "data" / "wechat_ai.db"
    path.parent.mkdir(parents=True)
    with sqlite3.connect(path) as connection:
        connection.executescript(V1_SQL)
    return path


def open_storage(root: str) -> int:
    # Top-level function for Windows multiprocessing spawn.
    return Storage(Path(root)).stats()["schema_version"]


def test_empty_initialization_and_repeat(storage):
    assert storage.stats()["schema_version"] == SCHEMA_VERSION
    backups = list((storage.path.parent / "backups").glob("*.db"))
    assert len(backups) == SCHEMA_VERSION
    for _ in range(3):
        Storage(storage.root)
    assert set(backups) == set((storage.path.parent / "backups").glob("*.db"))
    with storage._connection() as connection:
        assert connection.execute("PRAGMA foreign_keys").fetchone()[0] == 1
        assert connection.execute("PRAGMA busy_timeout").fetchone()[0] == 5000
        assert connection.execute("PRAGMA journal_mode").fetchone()[0] == "wal"
        integrity_check(connection)


def test_upgrade_v1_preserves_data_and_backup(tmp_path):
    path = make_v1(tmp_path)
    with sqlite3.connect(path) as connection:
        connection.execute("PRAGMA journal_mode=WAL")
        connection.execute("PRAGMA wal_autocheckpoint=0")
        connection.execute("UPDATE messages SET content='committed WAL history'")
        connection.commit()
        Storage(tmp_path)
    backup = next((path.parent / "backups").glob("pre-v2-*.db"))
    with sqlite3.connect(backup) as connection:
        assert connection.execute("PRAGMA user_version").fetchone()[0] == 1
        assert connection.execute("SELECT content FROM messages").fetchone()[0] == "committed WAL history"
    upgraded = Storage(tmp_path)
    assert upgraded.history("private", "Synthetic Friend", 8)[0]["content"] == "committed WAL history"
    with upgraded._connection() as connection:
        assert connection.execute("SELECT value FROM schema_meta WHERE key='schema_version'").fetchone()[0] == str(SCHEMA_VERSION)


def test_failed_migration_rolls_back_ddl_version_and_data(tmp_path):
    path = make_v1(tmp_path)
    def fail(connection):
        migrations.MIGRATIONS[2](connection)
        connection.execute("DELETE FROM messages")
        raise RuntimeError("Injected fault before commit")
    with pytest.raises(RuntimeError, match="Injected fault"):
        migrate(path, migrations={2: fail})
    with sqlite3.connect(path) as connection:
        assert connection.execute("PRAGMA user_version").fetchone()[0] == 1
        assert connection.execute("SELECT COUNT(*) FROM messages").fetchone()[0] == 1
        assert not connection.execute("SELECT name FROM sqlite_master WHERE name='principals'").fetchall()
    assert len(list((path.parent / "backups").glob("pre-v2-*.db"))) == 1
    migrate(path)  # Lock was released; an ordinary retry succeeds.


def test_refuse_newer_version_without_downgrade(storage):
    with storage._connection() as connection:
        connection.execute("PRAGMA user_version=100")
    before = storage.path.read_bytes()
    with pytest.raises(RuntimeError, match="拒绝降级"):
        Storage(storage.root)
    assert storage.path.read_bytes() == before


def test_bad_database_does_not_get_recreated(tmp_path):
    path = tmp_path / "data" / "wechat_ai.db"
    path.parent.mkdir()
    path.write_bytes(b"not a sqlite database")
    with pytest.raises(sqlite3.DatabaseError):
        Storage(tmp_path)
    assert path.read_bytes() == b"not a sqlite database"


def test_foreign_key_corruption_fails_integrity(storage):
    with sqlite3.connect(storage.path) as connection:
        connection.execute("INSERT INTO messages VALUES('bad',999,'user','incoming','test','failed',NULL,'t','t',NULL)")
    with pytest.raises(RuntimeError, match="完整性"):
        Storage(storage.root)


def test_lock_timeout_then_reuse(tmp_path):
    path = tmp_path / "migration.lock"
    with MigrationLock(path):
        with pytest.raises(TimeoutError):
            with MigrationLock(path, timeout=.05):
                pytest.fail("acquired same interprocess lock twice")
    with MigrationLock(path, timeout=.05):
        pass


def test_backup_retention_only_matches_auto_backups(tmp_path):
    for index in range(15):
        (tmp_path / f"pre-v2-20260101-{index:02}.db").write_text(str(index))
    manual = tmp_path / "manual-important.db"
    manual.write_text("keep")
    prune_backups(tmp_path)
    assert len(list(tmp_path.glob("pre-v*.db"))) == 10
    assert manual.read_text() == "keep"


def test_bot_panel_concurrent_migration_and_writes(tmp_path):
    with ProcessPoolExecutor(max_workers=4) as pool:
        assert list(pool.map(open_storage, [str(tmp_path)] * 8)) == [SCHEMA_VERSION] * 8
    storage = Storage(tmp_path)
    assert len(list((tmp_path / "data" / "backups").glob("*.db"))) == SCHEMA_VERSION
    def writer(index):
        s = Storage(tmp_path)
        item = s.add_incoming("private", "Synthetic Friend", str(index))
        s.complete_turn(item, "private", "Synthetic Friend", "reply")
        return s.stats()["ok"]
    with ThreadPoolExecutor(max_workers=6) as pool:
        assert all(pool.map(writer, range(40)))
    assert storage.stats()["message_count"] == 80
